### ISSUE TITLE
v8.9.7 - Cannot read properties of undefined

### ISSUE THREAD

**Issue by MstrDC** [sqren/backport#451]
When running version 8.9.7, I get the error below when running "npx backport" on my repo
Downgrading to version 8.9.4 fixes the issue.

{
    "level": "error",
    "message": "Unhandled exception: Cannot read properties of undefined (reading 'repository')",
    "metadata": {
        "stack": "TypeError: Cannot read properties of undefined (reading 'repository')\n    at getOptionsFromGithub (X:\\miles-core\\node_modules\\backport\\dist\\lib\\github\\v4\\getOptionsFromGithub\\getOptionsFromGithub.js:35:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getOptions (X:\\miles-core\\node_modules\\backport\\dist\\options\\options.js:57:31)\n    at async backportRun (X:\\miles-core\\node_modules\\backport\\dist\\backportRun.js:49:19)"
    },
    "timestamp": "2022-11-24 11:34:01"

**Comment by sqren** [comment]
Thanks for letting me know. I'll take a look over the weekend.
